baseURL = 'https://dev.gsanchietti.github.io/'
languageCode = 'en-us'
title = 'Dev Nethesis insights'
theme = 'beautifulhugo'
sectionPagesMenu = 'main'
enableEmoji = true
[Params]
  selfHosted = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

