name: Announce Weekly Updates

on:
  schedule:
    - cron: "0 7 */15 * 1" # Every 15 days on Monday at 7:00 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r announces/requirements.txt

      - name: Announce community updates for NethServer (English)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCOURSE_API_USERNAME: ${{ secrets.DISCOURSE_COMMUNITY_API_USERNAME }}
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_COMMUNITY_API_KEY }}
        run: |
          python announces/announce_weekly_updates.py \
            --discourse-host "https://community.nethserver.org" \
            --discourse-category-id 24 \
            --discourse-tags "NethServer" \
            --github-repository "NethServer/dev" \
            --product "NethServer" \
            --language "English"
          sleep 5

      - name: Announce community updates for NethSecurity (English)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCOURSE_API_USERNAME: ${{ secrets.DISCOURSE_COMMUNITY_API_USERNAME }}
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_COMMUNITY_API_KEY }}
        run: |
          python announces/announce_weekly_updates.py \
            --discourse-host "https://community.nethserver.org" \
            --discourse-category-id 24 \
            --discourse-tags "NethSecurity" \
            --github-repository "NethServer/nethsecurity" \
            --product "NethSecurity" \
            --language "English"
          sleep 5

      - name: Announce updates for NethVoice (English)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCOURSE_API_USERNAME: ${{ secrets.DISCOURSE_COMMUNITY_API_USERNAME }}
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_COMMUNITY_API_KEY }}
        run: |
          python announces/announce_weekly_updates.py \
            --discourse-host "https://community.nethserver.org" \
            --discourse-category-id 24 \
            --discourse-tags "NethVoice" \
            --github-repository "NethServer/dev" \
            --product "NethVoice" \
            --language "English"
          sleep 5

      - name: Announce updates for NethServer (Italian)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCOURSE_API_USERNAME: ${{ secrets.DISCOURSE_PARTNER_API_USERNAME }}
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_PARTNER_API_KEY }}
        run: |
          python announces/announce_weekly_updates.py \
            --discourse-host "https://community.nethserver.org" \
            --discourse-category-id 24 \
            --discourse-tags "NethServer" \
            --github-repository "NethServer/dev" \
            --product "NethServer" \
            --language "Italian"
          sleep 5

      - name: Announce updates for NethSecurity (Italian)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCOURSE_API_USERNAME: ${{ secrets.DISCOURSE_PARTNER_API_USERNAME }}
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_PARTNER_API_KEY }}
        run: |
          python announces/announce_weekly_updates.py \
            --discourse-host "https://community.nethserver.org" \
            --discourse-category-id 24 \
            --discourse-tags "NethSecurity" \
            --github-repository "NethServer/nethsecurity" \
            --product "NethSecurity" \
            --language "Italian"
          sleep 5

      - name: Announce updates for NethVoice (Italian)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCOURSE_API_USERNAME: ${{ secrets.DISCOURSE_PARTNER_API_USERNAME }}
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_PARTNER_API_KEY }}
        run: |
          python announces/announce_weekly_updates.py \
            --discourse-host "https://community.nethserver.org" \
            --discourse-category-id 24 \
            --discourse-tags "NethVoice" \
            --github-repository "NethServer/dev" \
            --product "NethVoice" \
            --language "Italian"
          sleep 5
